# Generated by Django 4.0.4 on 2022-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='username',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Логин'),
        ),
    ]
