version: '3'

services:
  #db:
  #  image: mysql:5.7
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: RoB_Db1_
  #    MYSQL_DATABASE: robobase
  #  ports:
  #    - "3306:3306"
  #  volumes:
  #    - mysql_data:/var/lib/mysql
  #  command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  web:
    build: .
    container_name: rdb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    #depends_on:
    #  - db

#volumes:
#  mysql_data: