# Generated by Django 4.0.4 on 2022-05-19 09:25

import database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_integrator_historicalintegrator_historicalclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Модель')),
                ('image', models.ImageField(blank=True, null=True, upload_to=database.models.RobotArm.get_file_path)),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалённый')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='RobotController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Контроллер')),
                ('image', models.ImageField(blank=True, null=True, upload_to=database.models.RobotController.get_file_path)),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалённый')),
            ],
            options={
                'verbose_name': 'Контроллер',
                'verbose_name_plural': 'Контроллеры',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRobotController',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Контроллер')),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалённый')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Контроллер',
                'verbose_name_plural': 'historical Контроллеры',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRobotArm',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Модель')),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалённый')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Модель',
                'verbose_name_plural': 'historical Модели',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
