# Generated by Django 4.0.4 on 2022-05-24 10:34

import database.models.RobotArm
from django.db import migrations, models
import django.db.models.deletion

from database.models.RobotArm import RobotArm


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_robotfile_historicalrobotfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='database.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='historicalrobotarm',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='robotarm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=RobotArm.get_file_path, verbose_name='Изображение'),
        ),
    ]
