# Generated by Django 4.0.4 on 2022-05-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_robotservice_historicalrobotservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobot',
            name='type',
            field=models.CharField(choices=[('kawasaki', 'Kawasaki'), ('kuka', 'KUKA'), ('fanuc', 'Fanuc'), ('abb', 'ABB'), ('yaskawa', 'Yaskawa'), ('okura', 'OKURA'), ('other', 'Другой')], default='kawasaki', max_length=255, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='robot',
            name='type',
            field=models.CharField(choices=[('kawasaki', 'Kawasaki'), ('kuka', 'KUKA'), ('fanuc', 'Fanuc'), ('abb', 'ABB'), ('yaskawa', 'Yaskawa'), ('okura', 'OKURA'), ('other', 'Другой')], default='kawasaki', max_length=255, verbose_name='Производитель'),
        ),
    ]
