# Generated by Django 4.0.4 on 2022-05-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_historicalrobot_type_robot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrobot',
            name='type',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='type',
        ),
    ]
