# Generated by Django 4.0.4 on 2022-05-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_robotvendor_historicalrobotvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobotarm',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.robotcontroller', verbose_name='Контроллер'),
        ),
        migrations.AddField(
            model_name='robotarm',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='database.robotcontroller', verbose_name='Контроллер'),
        ),
    ]
