# Generated by Django 4.0.4 on 2022-05-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_historicalrobotvendor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobotcontroller',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.robotvendor', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='robotcontroller',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='database.robotvendor', verbose_name='Производитель'),
        ),
    ]
