# Generated by Django 4.0.4 on 2022-05-24 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_robotcontroller_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobotfile',
            name='upload_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robotfile',
            name='upload_date',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
