# Generated by Django 4.0.4 on 2022-05-25 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_historicalrobotfile_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrobotservice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Обслуживание робота', 'verbose_name_plural': 'historical Обслуживания робота'},
        ),
        migrations.AlterModelOptions(
            name='robotservice',
            options={'verbose_name': 'Обслуживание робота', 'verbose_name_plural': 'Обслуживания робота'},
        ),
        migrations.RemoveField(
            model_name='historicalrobotservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='robotservice',
            name='name',
        ),
        migrations.AddField(
            model_name='historicalrobotservice',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='historicalrobotservice',
            name='description',
            field=models.TextField(default=' ', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalrobotservice',
            name='robot_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.robot', verbose_name='Робот'),
        ),
        migrations.AddField(
            model_name='robotservice',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='robotservice',
            name='description',
            field=models.TextField(default=' ', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='robotservice',
            name='robot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.robot', verbose_name='Робот'),
            preserve_default=False,
        ),
    ]
