# Generated by Django 4.0.4 on 2022-05-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0018_rename_robot_id_historicalrobotservice_robot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobot',
            name='added_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен'),
        ),
        migrations.AddField(
            model_name='robot',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен'),
        ),
    ]
