# Generated by Django 4.0.4 on 2022-07-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_historicalrobot_added_by_robot_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobotservice',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалённый'),
        ),
        migrations.AddField(
            model_name='historicalrobotvendor',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалённый'),
        ),
        migrations.AddField(
            model_name='robotservice',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалённый'),
        ),
        migrations.AddField(
            model_name='robotvendor',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалённый'),
        ),
        migrations.AlterField(
            model_name='historicalrobot',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.location', verbose_name='Текущее местоположение'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='database.location', verbose_name='Текущее местоположение'),
        ),
    ]
