# Generated by Django 4.0.4 on 2022-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_historicalrobotservice_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалённый'),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалённый'),
        ),
    ]
