# Generated by Django 4.0.4 on 2022-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_alter_historicalrobotfile_type_alter_robotfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobot',
            name='manufactured_date',
            field=models.CharField(blank=True, max_length=32, verbose_name='Дата производства (ММ/ГГГГ)'),
        ),
        migrations.AddField(
            model_name='robot',
            name='manufactured_date',
            field=models.CharField(blank=True, max_length=32, verbose_name='Дата производства (ММ/ГГГГ)'),
        ),
    ]
