# Generated by Django 4.0.4 on 2022-10-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_historicalrobot_manufactured_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион'),
        ),
    ]
