# Generated by Django 4.0.4 on 2022-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_robotseller_historicalrobotseller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrobotseller',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Поставщик', 'verbose_name_plural': 'historical Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='robotseller',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='historicalrobotseller',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='robotseller',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Поставщик'),
        ),
    ]
