# Generated by Django 4.0.4 on 2022-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_historicalrobot_seller_robot_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrobot',
            name='controller_sn',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Серийный номер контроллера'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='controller_sn',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Серийный номер контроллера'),
        ),
    ]
