# Generated by Django 4.0.4 on 2022-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_alter_historicalrobot_controller_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrobot',
            name='controller_sn',
            field=models.CharField(db_index=True, default=0, max_length=32, verbose_name='Серийный номер контроллера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='robot',
            name='controller_sn',
            field=models.CharField(db_index=True, default=0, max_length=32, verbose_name='Серийный номер контроллера'),
            preserve_default=False,
        ),
    ]
