# Generated by Django 4.0.4 on 2022-10-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_remove_historicalrobot_manufactured_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobotfile',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.robotservice', verbose_name='Относится к сервису'),
        ),
        migrations.AddField(
            model_name='robotfile',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.robotservice', verbose_name='Относится к сервису'),
        ),
    ]
