# Generated by Django 4.0.4 on 2022-10-26 13:07

import database.models.RobotController
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_historicalrobot_manufactured_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrobot',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='historicalrobotfile',
            name='type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('backup', 'Резервная копия'), ('report', 'Oтчет по работам'), ('check', 'Чек-лист'), ('other', 'Другое'), ('docs', 'Документы')], max_length=255, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='robotcontroller',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=database.models.RobotController.get_file_path),
        ),
        migrations.AlterField(
            model_name='robotfile',
            name='type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('backup', 'Резервная копия'), ('report', 'Oтчет по работам'), ('check', 'Чек-лист'), ('other', 'Другое'), ('docs', 'Документы')], max_length=255, verbose_name='Тип файла'),
        ),
    ]
