# Generated by Django 4.0.4 on 2022-10-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_alter_robotarm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrobot',
            name='seller',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.robotseller', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='robot',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='database.robotseller', verbose_name='Поставщик'),
        ),
    ]
