# Generated by Django 4.0.4 on 2022-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_alter_historicalrobotfile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
    ]
